[project]
name = "hbnb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.2",
    "flask-jwt-extended>=4.7.1",
    "flask-restx>=1.3.2",
    "sql>=2022.4.0",
    "sqlalchemy>=2.0.44",
]
